# Generated by Django 6.1.1 on 2026-09-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(auto_now_add=True)),
                ('appointment_time', models.TimeField(auto_now_add=True)),
                ('appointment_status', models.CharField(default='pending', max_length=20)),
                ('appointment_details', models.TextField()),
            ],
        ),
    ]
